name: Build and publish Docker images

on:
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      IMAGE_TAG:
        description: Docker image tag (a triggering Git tag takes precedence)
        required: false
        type: string
        default: latest

permissions:
  contents: read
  packages: write

jobs:
  docker:
    uses: iganets/.github/.github/workflows/docker.yml@main
    with:
      IGANET_BUILD_TYPE: Release
      IGANET_BUILD_CPUONLY: "OFF"
      IGANET_BUILD_DOCS: "OFF"
      IGANET_BUILD_PCH: "ON"
      IGANET_OPTIONAL: "examples"
      IGANET_WITH_GISMO: "ON"
      IGANET_WITH_MATPLOT: "OFF"
      IGANET_WITH_MPI: "OFF"
      IGANET_WITH_OPENMP: "ON"
      IMAGE_NAME: iganet
      IMAGE_TAG: ${{ inputs.IMAGE_TAG || 'latest' }}
      CPU_LABEL: cpu
      CPU_DEV_LABEL: cpu-dev
      CUDA_LABEL: cuda
      CUDA_DEV_LABEL: cuda-dev
      ROCM_LABEL: rocm
      ROCM_DEV_LABEL: rocm-dev      
      NJOBS: 1
